#!/bin/bash

# This scripts needs these variables to exist:
#
# OK
# FARMER_DATA_LOCATION
# FARMER_REVERSE_PROXY_PORT
# FARMER_REVERSE_PROXY_PORT_SSL
#

# Include utils
my_dir=`dirname $BASH_SOURCE`
source ${my_dir}/misc

echo ""
echo "${YELLOW}=== Creating and setting up Farmer dependent services ===${RESET}"
echo ""

    # Make sure Docker is installed.
    if ! command_exists docker; then
        echo "It seems Docker daemon is not installed here."

        if $(ask_confirm "Should I install Docker latest version?"); then
            farmer_install_docker
        fi
    fi

    echo "${YELLOW}1) Installing hub container...${RESET}"
        ensure_container_free farmer-hub

        if [ $? -eq ${OK} ]; then
            export consumer_username=farmer
            export consumer_password=$(generate_random)
            hub_admin_password=$(generate_random)

            docker run --name farmer-hub \
                -e RABBITMQ_PASS=${hub_admin_password} \
                -e CONSUMER_USERNAME=${consumer_username} \
                -e CONSUMER_PASSWORD=${consumer_password} \
                -p 5672:5672 \
                -p 15672:15672 \
                --hostname farmer \
                -d tutum/rabbitmq

            handle_container_error tutum/rabbitmq
            sleep 5

            echo " > Creating consumer user..."
            docker exec farmer-hub rabbitmqctl start_app
            docker exec farmer-hub rabbitmqctl add_user ${consumer_username} ${consumer_password}

            echo " > Allowing monitor access to consumer user..."
            docker exec farmer-hub rabbitmqctl set_user_tags ${consumer_username} monitoring
            curl -i -u admin:${hub_admin_password} -H "content-type:application/json" \
                 -XPUT -d'{"username":"${consumer_username}","vhost":"/","configure":".*","write":".*","read":".*"}' \
                 http://$(docker_get_ip farmer-hub):15672/api/permissions/%2f/${consumer_username}

            echo "${GREEN}Hub container is created.${RESET}"
        else
            echo "${GREEN}Hub container already exists.${RESET}"
        fi
    echo ""

    echo "${YELLOW}2) Installing database container...${RESET}"
        ensure_container_free farmer-database

        if [ $? -eq ${OK} ]; then
            mkdir -p /var/farmer/mysql
            # TODO -v ${FARMER_DATA_LOCATION}/mysql:/var/lib/mysql \
            docker run --name farmer-database \
                -e MYSQL_ROOT_PASSWORD=$(generate_random) \
                -e MYSQL_USER=farmer \
                -e MYSQL_PASSWORD=$(generate_random) \
                -e MYSQL_DATABASE=farmer \
                --hostname farmer \
                -d mysql:latest
            sleep 10

            handle_container_error tutum/mysql
            echo "${GREEN}Database container is created.${RESET}"
        else
            echo "${GREEN}Database container already exists.${RESET}"
        fi
    echo ""

    echo "${YELLOW}3) Installing reserve-proxy container...${RESET}"
        ensure_container_free_trivial farmer-reverse-proxy

        if [ $? -eq ${OK} ]; then
            export FARMER_REVERSE_PROXY_LOCATION=${FARMER_DATA_LOCATION}/proxy
            docker run --name farmer-reverse-proxy \
                -e FARMER_REVERSE_PROXY_LOCATION=${FARMER_REVERSE_PROXY_LOCATION} \
                -p ${FARMER_REVERSE_PROXY_PORT}:80 \
                -p ${FARMER_REVERSE_PROXY_PORT_SSL}:443 \
                -v ${FARMER_REVERSE_PROXY_LOCATION}:/etc/nginx/conf.d:rw \
                -d nginx

            handle_container_error nginx
            echo "${GREEN}Reverse-proxy container is created.${RESET}"
        else
            echo "${GREEN}Reverse-proxy container already exists.${RESET}"
        fi
    echo ""

echo ""
echo "${GREEN}=== Farmer services are created successfully ===${RESET}"
echo ""
