#!/bin/bash

# Include utils
my_dir=`dirname $BASH_SOURCE`
source ${my_dir}/misc

###
# Start Farmer
###

echo ""
echo "${YELLOW}=== Starting Farmer container ===${RESET}"
echo ""

    docker start farmer-server
    handle_container_error farmer-server

echo ""
echo "${GREEN}=== Farmer server is up successfully ===${RESET}"
echo ""
