---
  - name: Update apt
    sudo: yes
    apt:  update_cache=yes
    
  - name: Install system packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items: sys_packages
    
  - name: Add php ppa repository
    sudo: yes
    when: stage == "development"
    apt_repository: repo=ppa:ondrej/{{ php_ppa }} state=present

  - name: Update apt again (for php packages)
    sudo: yes
    apt:  update_cache=yes
    
  - name: Install extra packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items: extra_packages
