---
  - name: Install phpmyadmin
    sudo: yes
    when: stage == "development"
    apt:  pkg=phpmyadmin state=latest

  - name: Add phpmyadmin vhost to nginx
    sudo: yes
    when: stage == "development"
    template: src=phpmyadmin.j2 dest=/etc/nginx/sites-available/phpmyadmin

  - name: Enable phpmyadmin vhost
    sudo: yes
    when: stage == "development"
    command: ln -fs /etc/nginx/sites-available/phpmyadmin /etc/nginx/sites-enabled/phpmyadmin
    notify: restart nginx
    args:
      creates: /etc/nginx/sites-enabled/phpmyadmin

  - name: Set authentication type to config
    sudo: yes
    replace:
      dest=/etc/phpmyadmin/config.inc.php
      regexp="'cookie'"
      replace="'config'"

  - name: Enable no-password login for phpmyadmin
    sudo: yes
    lineinfile:
      dest=/etc/phpmyadmin/config.inc.php
      regexp="\s+(.*)AllowNoPassword"
      line="$cfg['Servers'][$i]['AllowNoPassword'] = TRUE;"