#!/bin/bash

#
# This script is meant for quick & easy install via command line
#

# Include utils
DIR=`dirname $BASH_SOURCE`
source ${DIR}/util/misc

# We need root access
if [[ $(id -u) -ne 0 ]]; then
    echo "Permission denied: run installer as root user"
    exit 1
fi

echo "${YELLOW}"
echo "===================================="
echo "|| Welcome to Farmer Installation ||"
echo "===================================="
echo "${RESET}"

###
# Preparation
###

    # Make sure Docker is installed.
    if ! command_exists docker; then
        echo "It seems Docker daemon is not installed here."
        read -r -p "Should I install Docker latest version? ${CYAN}[Y/n]:${RESET} " response
        response=${response:-y}
        if [[ ${response} =~ ^([yY][eE][sS]|[yY])$ ]]; then
            farmer_install_docker
        fi
    fi

    # Make sure jq is installed.
    if ! command_exists jq; then
        echo "It seems JQ json tool is not installed here."
        read -r -p "Should I install jq? ${CYAN}[Y/n]:${RESET} " response
        response=${response:-y}
        if [[ ${response} =~ ^([yY][eE][sS]|[yY])$ ]]; then
            apt-get install jq -y --force-yes
        fi
    fi

###
# Gather Required Info
###

    # Ask Farmer API Port
        echo -n "1) Which port should Farmer API listen to? ${CYAN}(Default: 5549):${RESET} "
        read FARMER_API_PORT
        echo ""
        export FARMER_API_PORT=${FARMER_API_PORT:-5549}

    # Ask Reverse Proxy Port
        echo    "2) Which port should Farmer reverse-proxy listen to?"
        echo -n "   This is where all PUBLIC http traffic should go to. ${CYAN}(Default: 80):${RESET} "
        read FARMER_REVERSE_PROXY_PORT
        export FARMER_REVERSE_PROXY_PORT=${FARMER_REVERSE_PROXY_PORT:-80}

        echo -n "   http(s) SSL traffic port? ${CYAN}(Default: 443):${RESET} "
        read FARMER_REVERSE_PROXY_PORT_SSL
        echo ""
        export FARMER_REVERSE_PROXY_PORT_SSL=${FARMER_REVERSE_PROXY_PORT_SSL:-443}

    # Ask Server IP
        MY_IP=$(my_ip)
        echo    "3) What is this server's public acessible IP address?"
        echo -n "   Used for adminstration UIs. ${CYAN}(Default: ${MY_IP}):${RESET} "
        read FARMER_HOST_IP
        echo ""
        export FARMER_HOST_IP=${FARMER_HOST_IP:-$MY_IP}
        farmer_check_host ${FARMER_HOST_IP}

    # Ask Docker API
        echo    "4) What is this server's Docker daemon API Address?"
        echo -n "   It should be accssible from within Farmer's container. ${CYAN}(Default: ${FARMER_HOST_IP}):${RESET} "
        read FARMER_DOCKER_API_HOST
        echo ""
        export FARMER_DOCKER_API_HOST=${FARMER_DOCKER_API_HOST:-$FARMER_HOST_IP}
        farmer_check_host ${FARMER_DOCKER_API_HOST}

        echo -n "5) What is Docker daemon API Port? ${CYAN}(Default: 4243):${RESET} "
        read FARMER_DOCKER_API_PORT
        echo ""
        export FARMER_DOCKER_API_PORT=${FARMER_DOCKER_API_PORT:-4243}

        export FARMER_DOCKER_API="tcp://${FARMER_DOCKER_API_HOST}:${FARMER_DOCKER_API_PORT}"

    # Ask Farmer Data Location
        echo -n "5) Where should I put box's data (e.g. cloned codes, database, proxy configs)? ${CYAN}(Default: /var/farmer):${RESET} "
        read FARMER_DATA_LOCATION
        echo ""
        export FARMER_DATA_LOCATION=${FARMER_DATA_LOCATION:-/var/farmer}
        mkdir -p ${FARMER_DATA_LOCATION}/box

###
# Installation
###

    source ${DIR}/util/build-services
    handle_error "building services"

    source ${DIR}/util/start-services
    handle_error "starting services"

    source ${DIR}/util/build-farmer
    handle_error "building farmer"

    source ${DIR}/util/start-farmer
    handle_error "starting farmer"

echo "${YELLOW}"
echo "===================================="
echo "|| Installation details:          ||"
echo "===================================="
echo "${RESET}"
echo "Server: ${CYAN}${FARMER_HOST_IP}${RESET} (or any address pointing to this machine)"
echo "Server Port: ${CYAN}${FARMER_API_PORT}${RESET}"
echo "Docker API: ${CYAN}${FARMER_DOCKER_API}${RESET}"
echo "Data Location: ${CYAN}${FARMER_DATA_LOCATION}${RESET}"
echo "Reverse Proxy Config Path: ${CYAN}${FARMER_REVERSE_PROXY_CONF_PATH}${RESET}"
echo ""
echo "Hub Admin: ${CYAN}http://${FARMER_HOST_IP}:15672/${RESET}"
echo "    Hub Username: ${CYAN}admin${RESET}"
echo "    Hub Password: ${CYAN}${hub_admin_pass}${RESET}"
echo "    Admin Amqp URI: ${CYAN}${FARMER_ADMIN_AMQP_URI}${RESET}"
echo "    Consumer Amqp URI: ${CYAN}${FARMER_CONSUMER_AMQP_URI}${RESET}"
echo ""
echo "Database: ${CYAN}${FARMER_DB_HOST}:${FARMER_DB_PORT}${RESET}"
echo "    DB Name: ${CYAN}${FARMER_DB_NAME}${RESET}"
echo "    DB Username: ${CYAN}${FARMER_DB_USERNAME}${RESET}"
echo "    DB Password: ${CYAN}${FARMER_DB_PASSWORD}${RESET}"
echo ""
echo "Git SSH Public Key: ${CYAN}${FARMER_DATA_LOCATION}/keys/gitkey_rsa.pub${RESET}"
echo "    You can copy and use this public key in your git client to allow Farmer to clone repositories."
echo ""
echo "    You may use one of the commands below to copy your ssh key:"
echo "      ${YELLOW}xclip -selection clipboard < ${FARMER_DATA_LOCATION}/keys/gitkey_rsa.pub${RESET}"
echo "      to store public key in your clipboard using xclip,"
echo "      or"
echo "      ${YELLOW}cat ${FARMER_DATA_LOCATION}/keys/gitkey_rsa.pub${RESET}"
echo "      to manually copy public key from terminal window."
echo ""
echo "${GREEN}"
echo "===================================="
echo "|| Farmer successfully installed. ||"
echo "===================================="
echo "${RESET}"
