#!/bin/bash

# Include utils
DIR=`dirname $BASH_SOURCE`
source ${DIR}/util/misc

source ${DIR}/util/start-services
handle_error "starting services"

source ${DIR}/util/start-farmer
handle_error "starting farmer"

echo "${YELLOW}Gather required information from services' containers...${RESET}"

    # Farmer
    export FARMER_HOST_IP=$(docker_get_env farmer-server FARMER_HOST_IP)
    export FARMER_API_PORT=$(docker_get_env farmer-server FARMER_API_PORT)
    export FARMER_DOCKER_API=$(docker_get_env farmer-server FARMER_DOCKER_API)
    export FARMER_DATA_LOCATION=$(docker_get_env farmer-server FARMER_DATA_LOCATION)

    # Reverse-proxy
    export FARMER_REVERSE_PROXY_CONF_PATH=$(docker_get_env farmer-server FARMER_REVERSE_PROXY_CONF_PATH)

    # Database
    export FARMER_DB_USERNAME=$(docker_get_env farmer-server FARMER_DB_USERNAME)
    export FARMER_DB_PASSWORD=$(docker_get_env farmer-server FARMER_DB_PASSWORD)
    export FARMER_DB_HOST=$(docker_get_env farmer-server FARMER_DB_HOST)
    export FARMER_DB_PORT=$(docker_get_env farmer-server FARMER_DB_PORT)
    export FARMER_DB_NAME=$(docker_get_env farmer-server FARMER_DB_NAME)

    # Hub
    export FARMER_CONSUMER_AMQP_URI=$(docker_get_env farmer-server FARMER_CONSUMER_AMQP_URI)
    export FARMER_ADMIN_AMQP_URI=$(docker_get_env farmer-server FARMER_ADMIN_AMQP_URI)
    export hub_admin_pass=$(docker_get_env farmer-hub RABBITMQ_PASS)

echo "${YELLOW}"
echo "===================================="
echo "|| Details:                       ||"
echo "===================================="
echo "${RESET}"
echo "Server: ${CYAN}${FARMER_HOST_IP}${RESET} (or any address pointing to this machine)"
echo "Server Port: ${CYAN}${FARMER_API_PORT}${RESET}"
echo "Docker API: ${CYAN}${FARMER_DOCKER_API}${RESET}"
echo "Data Location: ${CYAN}${FARMER_DATA_LOCATION}${RESET}"
echo "Reverse Proxy Config Path: ${CYAN}${FARMER_REVERSE_PROXY_CONF_PATH}${RESET}"
echo ""
echo "Hub Admin: ${CYAN}http://${FARMER_HOST_IP}:15672/${RESET}"
echo "    Hub Username: ${CYAN}admin${RESET}"
echo "    Hub Password: ${CYAN}${hub_admin_pass}${RESET}"
echo "    Admin Amqp URI: ${CYAN}${FARMER_ADMIN_AMQP_URI}${RESET}"
echo "    Consumer Amqp URI: ${CYAN}${FARMER_CONSUMER_AMQP_URI}${RESET}"
echo ""
echo "Database: ${CYAN}${FARMER_DB_HOST}:${FARMER_DB_PORT}${RESET}"
echo "    DB Name: ${CYAN}${FARMER_DB_NAME}${RESET}"
echo "    DB Username: ${CYAN}${FARMER_DB_USERNAME}${RESET}"
echo "    DB Password: ${CYAN}${FARMER_DB_PASSWORD}${RESET}"
echo ""
echo "Git SSH Public Key: ${CYAN}${FARMER_DATA_LOCATION}/keys/gitkey_rsa.pub${RESET}"
echo "    You can copy and use this public key in your git client to allow Farmer to clone repositories."
echo ""
echo "    You may use one of the commands below to copy your ssh key:"
echo "      ${YELLOW}xclip -selection clipboard < ${FARMER_DATA_LOCATION}/keys/gitkey_rsa.pub${RESET}"
echo "      to store public key in your clipboard using xclip,"
echo "      or"
echo "      ${YELLOW}cat ${FARMER_DATA_LOCATION}/keys/gitkey_rsa.pub${RESET}"
echo "      to manually copy public key from terminal window."
echo ""
echo "${GREEN}"
echo "===================================="
echo "|| Farmer successfully started. ||"
echo "===================================="
echo "${RESET}"
