---
- name: Install npm dependencies
  npm: path=/var/www

- name: create application config file
  sudo: yes
  template: src=farmer.conf.j2 dest=/var/www/farmer.conf.js

- name: install docker.io
  sudo: yes
  shell: apt-get install -y docker.io

- name: ready nginx to enable docker rest api
  sudo: yes
  shell: sudo sed -i 's/user .*;/user root;/' /etc/nginx/nginx.conf

- name: docker rest api config file
  sudo: yes
  shell: tee /etc/nginx/sites-enabled/docker <<EOF
         upstream docker {
           server unix:/var/run/docker.sock;
         }

         server {
           listen 4242 default_server;
           location / {
             proxy_pass http://docker;
             auth_basic_user_file /etc/nginx/.htpasswd;
             auth_basic "Access restricted";
           }
         }
         EOF
#- name: "Install forever (to run Node.js app)."
#  sudo: yes
#  npm: name=forever global=yes state=latest
#
#- name: "Check list of Node.js apps running."
#  command: forever list
#  register: forever_list
#  changed_when: false
#
#- name: "Start example Node.js app."
#  command: forever start /var/www/src/index.js
#  when: "forever_list.stdout.find('/path/to/app.js') == -1"