---
  - name: Install nginx
    sudo: yes
    when: stage == "development"
    apt:  pkg=nginx state=latest

  - name: Ensure nginx log directory exists
    sudo: yes
    when: stage == "development"
    file: dest=/var/log/nginx/ravaj state=directory

  - name: Change default nginx site
    when: stage == "development"
    sudo: yes
    template: src=default.j2 dest=/etc/nginx/conf.d/default.conf
    notify: restart nginx